
contact:
  name: "my_test_stub"
  server: "tcp://dev.joyteam.cc:1883"
  username: "test"
  password: "123456"

ices:
  - "stun:dev.joyteam.cc:3478"
  # - "stun:stun.l.google.com:19302"
  # - "stun:stun.xten.com:3478"
  # - "stun:stun.voipbuster.com:3478"
  # - "stun:stun.sipgate.net:3478"
  # - "stun:stun.ekiga.net:3478"
  # - "stun:stun.ideasip.com:3478"
  # - "stun:stun.schlund.de:3478"
  # - "stun:stun.voiparound.com:3478"
  # - "stun:stun.voipbuster.com:3478"
  # - "stun:stun.voipstunt.com:3478"
  # - "stun:stun.counterpath.com:3478"
  # - "stun:stun.1und1.de:3478"
  # - "stun:stun.gmx.net:3478"
  # - "stun:stun.callwithus.com:3478"
  # - "stun:stun.counterpath.net:3478"
  # - "stun:stun.internetcalls.com:3478"
  # - "stun:numb.viagenie.ca:3478"

stubs:
  - name: "ssh_stub1"
    enable: true
    upstream: "127.0.0.1:22"
  - name: "vnc_stub1"
    enable: false
    upstream: "127.0.0.1:5901"
