
contacts:
  name: "my_test_proxy"
  server: "tcp://dev.joyteam.cc:1883"
  username: "test"
  password: "123456"

ice:
  - "stun:stun.l.google.com:19302"

proxy:
  listen: ":50022"
  stub: "my_test_stub"

